import logging
import psycopg2
import psycopg2.extras
from settings import DATABASE_NAME, USERNAME, PASSWORD, DB_HOST, TABLE_NAME

logger = logging.getLogger(__name__)

_conn = None
_cursor = None

CREATE_TABLE_SQL = f'''
CREATE TABLE {TABLE_NAME} (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src_port INT NOT NULL,
    dst_port INT NOT NULL,
    protocol INT NOT NULL,
    flow_duration FLOAT NOT NULL,
    flow_byts_s FLOAT NOT NULL,
    flow_pkts_s FLOAT NOT NULL,
    fwd_pkts_s FLOAT NOT NULL,
    bwd_pkts_s FLOAT NOT NULL,
    tot_fwd_pkts INT NOT NULL,
    tot_bwd_pkts INT NOT NULL,
    totlen_fwd_pkts INT NOT NULL,
    totlen_bwd_pkts INT NOT NULL,
    fwd_pkt_len_max FLOAT NOT NULL,
    fwd_pkt_len_min FLOAT NOT NULL,
    fwd_pkt_len_mean FLOAT NOT NULL,
    fwd_pkt_len_std FLOAT NOT NULL,
    bwd_pkt_len_max FLOAT NOT NULL,
    bwd_pkt_len_min FLOAT NOT NULL,
    bwd_pkt_len_mean FLOAT NOT NULL,
    bwd_pkt_len_std FLOAT NOT NULL,
    pkt_len_max INT NOT NULL,
    pkt_len_min INT NOT NULL,
    pkt_len_mean FLOAT NOT NULL,
    pkt_len_std FLOAT NOT NULL,
    pkt_len_var FLOAT NOT NULL,
    fwd_header_len INT NOT NULL,
    bwd_header_len INT NOT NULL,
    fwd_seg_size_min INT NOT NULL,
    fwd_act_data_pkts INT NOT NULL,
    flow_iat_mean FLOAT NOT NULL,
    flow_iat_max FLOAT NOT NULL,
    flow_iat_min FLOAT NOT NULL,
    flow_iat_std FLOAT NOT NULL,
    fwd_iat_tot FLOAT NOT NULL,
    fwd_iat_max FLOAT NOT NULL,
    fwd_iat_min FLOAT NOT NULL,
    fwd_iat_mean FLOAT NOT NULL,
    fwd_iat_std FLOAT NOT NULL,
    bwd_iat_tot FLOAT NOT NULL,
    bwd_iat_max FLOAT NOT NULL,
    bwd_iat_min FLOAT NOT NULL,
    bwd_iat_mean FLOAT NOT NULL,
    bwd_iat_std FLOAT NOT NULL,
    fwd_psh_flags INT NOT NULL,
    bwd_psh_flags INT NOT NULL,
    fwd_urg_flags INT NOT NULL,
    bwd_urg_flags INT NOT NULL,
    fin_flag_cnt INT NOT NULL,
    syn_flag_cnt INT NOT NULL,
    rst_flag_cnt INT NOT NULL,
    psh_flag_cnt INT NOT NULL,
    ack_flag_cnt INT NOT NULL,
    urg_flag_cnt INT NOT NULL,
    ece_flag_cnt INT NOT NULL,
    down_up_ratio FLOAT NOT NULL,
    pkt_size_avg FLOAT NOT NULL,
    init_fwd_win_byts INT NOT NULL,
    init_bwd_win_byts INT NOT NULL,
    active_max FLOAT NOT NULL,
    active_min FLOAT NOT NULL,
    active_mean FLOAT NOT NULL,
    active_std FLOAT NOT NULL,
    idle_max FLOAT NOT NULL,
    idle_min FLOAT NOT NULL,
    idle_mean FLOAT NOT NULL,
    idle_std FLOAT NOT NULL,
    fwd_byts_b_avg FLOAT NOT NULL,
    fwd_pkts_b_avg FLOAT NOT NULL,
    bwd_byts_b_avg FLOAT NOT NULL,
    bwd_pkts_b_avg FLOAT NOT NULL,
    fwd_blk_rate_avg FLOAT NOT NULL,
    bwd_blk_rate_avg FLOAT NOT NULL,
    fwd_seg_size_avg FLOAT NOT NULL,
    bwd_seg_size_avg FLOAT NOT NULL,
    cwe_flag_count INT NOT NULL,
    subflow_fwd_pkts INT NOT NULL,
    subflow_bwd_pkts INT NOT NULL,
    subflow_fwd_byts INT NOT NULL,
    subflow_bwd_byts INT NOT NULL,
    src_ip VARCHAR(100) NOT NULL,
    dst_ip VARCHAR(100) NOT NULL,
    title VARCHAR(50) NOT NULL,
    is_visible BOOLEAN NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
'''


def get_connection():
    global _conn, _cursor
    if _conn is None or _conn.closed:
        _conn = psycopg2.connect(
            dbname=DATABASE_NAME,
            user=USERNAME,
            password=PASSWORD,
            host=DB_HOST,
        )
        _cursor = _conn.cursor()
        _ensure_table(_cursor, _conn)
    return _conn, _cursor


def _ensure_table(cursor, conn):
    cursor.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
        (TABLE_NAME,),
    )
    if cursor.fetchone() is None:
        cursor.execute(CREATE_TABLE_SQL)
        conn.commit()
        logger.info("Таблица '%s' создана.", TABLE_NAME)


def save_attack(packets: list, attack_name: str) -> None:
    conn, cursor = get_connection()
    for packet in packets:
        keys = list(packet.keys())
        values = list(packet.values())
        columns = ', '.join(keys)
        placeholders = ', '.join(['%s'] * len(values))
        sql = (
            f"INSERT INTO {TABLE_NAME} ({columns}, title, is_visible, timestamp) "
            f"VALUES ({placeholders}, %s, TRUE, NOW())"
        )
        try:
            cursor.execute(sql, values + [attack_name])
        except Exception:
            logger.exception("Ошибка при сохранении пакета в БД.")
            conn.rollback()
            return
    conn.commit()


def get_visible_attacks() -> list:
    _, cursor = get_connection()
    sql = (
        f"SELECT id, title, src_ip, dst_ip, timestamp "
        f"FROM {TABLE_NAME} WHERE is_visible = TRUE ORDER BY id"
    )
    cursor.execute(sql)
    rows = cursor.fetchall()
    return [
        {
            'id': str(row[0]),
            'title': row[1],
            'src_ip': row[2],
            'dst_ip': row[3],
            'timestamp': row[4],
        }
        for row in rows
    ]


def set_hidden(attack_id) -> None:
    conn, cursor = get_connection()
    cursor.execute(
        f"UPDATE {TABLE_NAME} SET is_visible = FALSE WHERE id = %s",
        (attack_id,),
    )
    conn.commit()


def export_attacks_csv(filepath: str) -> int:
    """Экспортирует все атаки в CSV-файл. Возвращает количество строк."""
    import csv
    _, cursor = get_connection()
    cursor.execute(f"SELECT * FROM {TABLE_NAME} ORDER BY id")
    rows = cursor.fetchall()
    colnames = [desc[0] for desc in cursor.description]
    with open(filepath, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(colnames)
        writer.writerows(rows)
    logger.info("Экспортировано %d записей в '%s'.", len(rows), filepath)
    return len(rows)


def get_attack_stats() -> dict:
    """Возвращает статистику по типам атак."""
    _, cursor = get_connection()
    cursor.execute(
        f"SELECT title, COUNT(*) FROM {TABLE_NAME} GROUP BY title ORDER BY COUNT(*) DESC"
    )
    return {row[0]: row[1] for row in cursor.fetchall()}
