# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'incident_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from settings import WINDOW_WIDTH
import db

class Ui_item(QtWidgets.QWidget):
    def __init__(self, attack):

        super().__init__()

        self.id = attack['id']

        self.id_title = QtWidgets.QLabel(self)
        self.id_title.setGeometry(QtCore.QRect(0, 0, WINDOW_WIDTH, 20))
        self.id_title.setAlignment(QtCore.Qt.AlignCenter)
        self.id_title.setObjectName("id")
        self.id_title.setText(f"Инцидент {attack['id']}")

        self.title = QtWidgets.QLabel(self)
        self.title.setGeometry(QtCore.QRect(0, 20, WINDOW_WIDTH, 30))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.title.setText(attack['title'])

        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 40, WINDOW_WIDTH, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.src_ip = QtWidgets.QLabel(self)
        self.src_ip.setGeometry(QtCore.QRect(0, 60, 381, 16))
        self.src_ip.setObjectName("src_ip")
        self.src_ip.setText(attack['src_ip'])
        

        self.dst_ip = QtWidgets.QLabel(self)
        self.dst_ip.setGeometry(QtCore.QRect(0, 80, 381, 16))
        self.dst_ip.setObjectName("dst_ip")
        self.dst_ip.setText(attack['dst_ip'])

        self.timestamp = QtWidgets.QLabel(self)
        self.timestamp.setGeometry(QtCore.QRect(0, 100, 381, 16))
        self.timestamp.setObjectName("timestamp")
        self.timestamp.setText(attack['timestamp'].strftime('%Y-%m-%d %H:%M:%S'))

        self.hide = QtWidgets.QPushButton(self)
        self.hide.setGeometry(QtCore.QRect(WINDOW_WIDTH-20, 10, 21, 21))
        self.hide.setObjectName("hide")
        self.hide.setText("x")
        self.hide.clicked.connect(self.click_hide)

        self.endline = QtWidgets.QFrame(self)
        self.endline.setGeometry(QtCore.QRect(0, 110, WINDOW_WIDTH, 16))
        self.endline.setFrameShape(QtWidgets.QFrame.HLine)
        self.endline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.endline.setObjectName("endline")

    def click_hide(self):
        print(f'Скрываю атаку {self.id}')
        self.list.takeItem(self.list.row(self.item))
        db.set_hidden(self.id)
    